# Generated by Django 2.2.4 on 2021-03-26 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0002_comment_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='cmt_content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='msg_content',
        ),
    ]
